[template]
cargo_generate_version = ">=0.17.4"
ignore = ["README.md", "scripts"]

[hooks]
pre = ["pre-script.rhai"]

[placeholders.chip]
type = "string"
prompt = "Which MCU to target (see `probe-rs chip list`)?"
default = "STM32F411CE"
